---
title: "Homework 2"
author: "Andrew Stewart & Madeleine Augostini"
date: "6/3/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
require(tidyverse)
```

# Question 2:

```{r}
z <- matrix( nrow = 3, ncol = 5)
for (m in 1:3) {
  for (n in 1:5) {
    z[m, n] <- (n-m)
  }
}
print(z)
```

# Question 3:

```{r}
X <- list(12,14,15,18,19)
Mean <- list(8,14,20,22,30)
sd <- list(10,18,28,34,40)

## a
pmap_dbl(list(X,Mean,sd), max)

## b
pmap_dbl(list(X,Mean,sd), function(X, Mean, sd) (X-Mean)/sd) # z score formula: z = (X-Mean)/sd

## c
pmap_dbl(list(X,Mean,sd), function(X, Mean, sd) (X - Mean)/(sd/sqrt(5)))
```

# Question 4:

```{r}
## a

V = c(10,15,17,22,32,38,42)
keep(V, V<20)

## b

discard(V,V<20)
```


# Question 5:

```{r}
U = list(10,15,"mary", 22,32,"james", 42)
map(U, safely(~.x +15))
```

The safely function applies the function to all of the values in the list. If there is an error it throws an error result before moving onto the next instance. In this case the function adds 15 to all  numeric values while explaining that the non-numeric values are unable to be operated on.